### PR TITLE
Colors for orientation information

### LINKED ISSUE #550: Orientation information in the renderer
Once the orientation labelling (#243) is done, we need to display this information in the renderered diagram.

Here are some ideas:
- different colours (how will this interact with the different shades for points, wires, regions)
- asymmetric boxes for the points (related to #519)
- arrows on the wires (#553)
- dashed/dotted wires?
- flip normals in GL

### PR DESCRIPTION
**Pull request by thud**
Closes #550.

### CODE REVIEW

**Comment by thud** [comment]
This is still early in prototype phase, trialling different ways of encoding orientation in the colours of rendered generators.

I have also used this opportunity to switch the internal scalar for colors to `T = f32` from `T = u8`, which should give slightly more accurate colour operations and avoids loss of precision for `gl` rendering etc.

**Comment by thud** [comment]
In hindsight, it's likely not a good idea to make the change to `T = f32`, given that it will break the serialisation code and therefore imports for previously generated diagrams/signatures.

**Comment by calintat** [comment]
> In hindsight, it's likely not a good idea to make the change to `T = f32`, given that it will break the serialisation code and therefore imports for previously generated diagrams/signatures.

Not a problem, I literally broke serialization on the labelled branch this morning :)

**Comment by jamievicary** [comment]
Looking great! But we need to tweak the values I think. What have you used at the moment for the 9 values, can you list the nine saturation/lightness values you have used?

**Comment by calintat** [comment]
Thanks Jasper! We actually need three different saturation levels per generator instead of two. These correspond to the three different orientations (-1, 0, 1). So there will be 9 CSS classes in total.

**Comment by calintat** [comment]
> Looking great! But we need to tweak the values I think. What have you used at the moment for the 9 values, can you list the nine saturation/lightness values you have used?

I agree! I can literally not tell them apart right now (granted I am colourblind). Honestly I still think arrows and different shapes would be a better way to tell inverses apart than colours.

**Comment by thud** [comment]
Yeah, I personally agree about having arrows and boxes but (especially for 3d) colours is a good option to have.
All the colour modifications are made in `homotopy-graphics/src/svg.rs` so for exact numbers look there.

The saturation factors as of now are:
| orientation | saturation |
|----------|------|
| forward  | 0    |
| zero?    |      |
| inverted | -0.3 |

The lightening factors as of now (unchanged) are:
| codimension | lightness |
|----------|------|
| point   | 0    |
| wire    | 0.05 |
| surface | 0.1  |

The factors are applied by `palette` (documented [here](https://ogeon.github.io/docs/palette/master/palette/trait.Saturate.html) for saturation).

I think we should also consider using `palette` from the `crates` registry instead of the `github` because they seem to keep changing their API (at least in the docs).

**Comment by jamievicary** [comment]
Hi Jasper, I cannot see yet how this implements the 9 saturation/lightness values described in issue #550, can you give more detail please.

**Comment by doctorn** [comment]
> In hindsight, it's likely not a good idea to make the change to `T = f32`, given that it will break the serialisation code and therefore imports for previously generated diagrams/signatures.

Sounds like time for some `obake` antics 🤩

**Comment by calintat** [comment]
Should we try -0.25 for zero and -0.5 for inverses? We can tweak these later.

**Comment by jamievicary** [comment]
I'm making further comments in the issue #550

**Comment by thud** [comment]
@jamievicary, I've added a temporary set of sliders in the settings panel for quickly setting lightnesses. This does not yet implement 'fixed' colour lightness modifications (with wrapping etc.).

**Comment by jamievicary** [comment]
Excellent, do these serialise with the workspace?

**Comment by thud** [comment]
Not at the moment, but they could do if needed?

**Comment by calintat** [comment]
The slider of inverse wire lightness doesn't seem to be working.

**Comment by thud** [comment]
> The slider of inverse wire lightness doesn't seem to be working.
Yup, fixed now.

**Comment by thud** [comment]
Todo:
- [ ] Colours for tikz, manim, gl etc.
- [ ] Colours should not change when entering slices.

**Comment by thud** [comment]
Yup ok. Do colours look right now? I think this is accurate to Jamie's formula.

**Comment by calintat** [comment]
I tried doing a snake and the inverse wire looks almost white:

homotopy_io_export-2

Honestly I think this idea is fundamentally flawed, it's too much information to encode using only colours.

**Comment by thud** [comment]
Hmm yeah, I'll see if I can quickly get a better colour solution prototyped.

**Comment by thud** [comment]
Alright, I have a solution which works pretty well for the time being (all the preset colours look alright in different orientations though the black and white presets have similar looking inverses). Unless someone is unhappy with this change, I'll get this merged very soon.

I've added a note which explains how colours are calculated in the most recent commit.

https://github.com/homotopy-io/homotopy-rs/blob/66febb5190b0005df2e67c0a2e8b933a734f9629/homotopy-graphics/src/style.rs#L57-L74

**Comment by thud** [comment]
Alright, I've implemented colours as decided by Jamie. This is to be merged imminently.

https://github.com/homotopy-io/homotopy-rs/blob/1c6f8b2f894915b02e0b795bfde2115371fcf4e1/homotopy-graphics/src/style.rs#L51-L76

**Comment by jamievicary** [comment]
Thanks Jasper this is great. Next can you please make sure the colours are being correctly displayed in 3d and 4d please.

**Pull request merged**
