### PR TITLE
Converted layout to using good_lp

### PR DESCRIPTION
**Pull request by regular-citizen**
The goal is then to switch to an underlying highs.

### CODE REVIEW

**Comment by calintat** [comment]
This is amazing, thanks Chiara! What's stopping us from switching to HiGHS now?

**Comment by regular-citizen** [comment]
In theory "just switching feature flags on good_lp". I'm writing a patch to do that cleanly.

I've given a highs version a try, and I have some good news and some bad news. Good news is that it is way faster than minilp, and in a couple seconds can work out the 4d rendering of Eckmann-Hilton. Bad news is that it gets layout wrong, in the sense that some wires go completely off.

Three things that could be going on with that:
- The ".sorted" lines that I removed were actually necessary (the only places that use that are commutative operations),
- I messed up the weak constraints (I checked and I'm using .geq properly, I think).
- Layout is underspecified as a LP problem, and we were simply used to the "minilp" flavour of solutions.

I'll shortly upload a patch to show what that looks like.

**Comment by calintat** [comment]
Fantastic news! It is definitely the case that layout is underspecified as a problem. In fact there are several open issues about further "desirable" constraints we could impose which would reduce the solution set. I don't think the sorting made any difference, if I recall correctly it was there for debug purposes.

I checked your code and everything looks correct to me. Moreover, this passes the tests so clearly it gives the same solutions as the version on master. I suggest we merge this now and then we figure out how to get it to work with HiGHS.

**Comment by regular-citizen** [comment]
> Fantastic news! It is definitely the case that layout is underspecified as a problem. In fact there are several open issues about further "desirable" constraints we could impose which would reduce the solution set. I don't think the sorting made any difference, if I recall correctly it was there for debug purposes.
> 
> I checked your code and everything looks correct to me. Moreover, this passes the tests so clearly it gives the same solutions as the version on master. I suggest we merge this now and then we figure out how to get it to work with HiGHS.

It passes the tests because this version is still running minilp (under good_lp). The highs version is not "slightly off", it makes EH unworkable as a 2d diagram.

**Comment by regular-citizen** [comment]
CopyQ hYRbjJ

**Comment by doctorn** [comment]
I know nothing about constraint programming but it looks like some of the nodes near the target aren't being constrained to appear above their inputs?

**Comment by calintat** [comment]
> > Fantastic news! It is definitely the case that layout is underspecified as a problem. In fact there are several open issues about further "desirable" constraints we could impose which would reduce the solution set. I don't think the sorting made any difference, if I recall correctly it was there for debug purposes.
> > I checked your code and everything looks correct to me. Moreover, this passes the tests so clearly it gives the same solutions as the version on master. I suggest we merge this now and then we figure out how to get it to work with HiGHS.
> 
> It passes the tests because this version is still running minilp (under good_lp). The highs version is not "slightly off", it makes EH unworkable as a 2d diagram.

Yes that's what I meant. Clearly your PR implements the "same" minilp problem because otherwise it would give different results, so you must have implemented the same constraints I did.

**Comment by calintat** [comment]
> CopyQ hYRbjJ

Woah, that is weird! Do smaller examples work fine?

**Comment by calintat** [comment]
> I know nothing about constraint programming but it looks like some of the nodes near the target aren't being constrained to appear above their inputs?

Layout is implemented inductively so what we're seeing with the "nodes not appearing above their inputs" is because the 1D layout is off.

**Comment by regular-citizen** [comment]
Some tiny ones do:
CopyQ beprbU
CopyQ WysEUb

Others don't:
CopyQ ZtDHIB

**Comment by regular-citizen** [comment]
Smallest divergence is braid_5.
This is HiGHS layout:
CopyQ ULUqaw

This is old layout:
CopyQ TAstoe

I've even managed to get a failure to solve the 3d layout for an identity wire.

**Comment by calintat** [comment]
Great, thanks for the examples Chiara! I think I may have a hunch or two how to fix this.

Could you please push your patch switching to HiGHS? If you want, you could merge this PR and make a new one.

**Comment by calintat** [comment]
Also I'm dying to know how much faster this really is. Do any of the knots in #707 work?

**Comment by regular-citizen** [comment]
> Great, thanks for the examples Chiara! I think I may have a hunch or two how to fix this.
> 
> Could you please push your patch switching to HiGHS? If you want, you could merge this PR and make a new one.

Let's do this.

> Also I'm dying to know how much faster this really is. Do any of the knots in #707 work?

Haven't tried and doing a clean switch to highs is a bit harder than expected due to feature flag woes (that I'm patching up). I also accidentally closed the tab in which I had the highs version, so you're gonna need to wait 5 mins to know.

**Pull request merged**
