### PR TITLE
refactor image export button

### PR DESCRIPTION
**Pull request by H-Yulong**
Refactor image export button so that it's in the top part of the sidebar.
Also added checkboxes for TikZ and Manim export options.

### CODE REVIEW

**Comment by regular-citizen** [comment]
Thanks for this Yulong, it looks great!

I've written up the patch for turning off the braidings on tikz, it may make sense to get it into this PR.
For some reason I cannot checkout your feature branch, any chance you could apply it before merging?
[no_braids.txt](https://github.com/homotopy-io/homotopy-rs/files/9468088/no_braids.txt)

**Comment by regular-citizen** [comment]
Thank you so much!

**Comment by H-Yulong** [comment]
@regular-citizen Thanks! Please also test and see if the options work

**Comment by regular-citizen** [comment]
Works beautifully!

**Review by regular-citizen — APPROVED** [review]
This look good to merge as far as I am concerned, thanks Yulong.

**Pull request merged**
