### PR TITLE
Integrated FileSaver.js

### PR DESCRIPTION
**Pull request by regular-citizen**
SaveAs doesn't really do saving as on Firefox/Linux and Chromium/Linux.

### CODE REVIEW

**Comment by calintat** [comment]
This doesn't work on my Mac on any of Safari, Firefox, or Chrome.

**Comment by NickHu** [comment]
This library hasn't been updated in two years. There's a new fs API, and basically the call we want is https://developer.mozilla.org/en-US/docs/Web/API/Window/showSaveFilePicker. Unfortunately, it's experimental and isn't available on all browsers. Fortunately, it can be polyfilled quite easily: https://github.com/jimmywarting/native-file-system-adapter/

**Comment by regular-citizen** [comment]
> This doesn't work on my Mac on any of Safari, Firefox, or Chrome.

Yeah it was mostly a demo of "saveAs" actually just being a polyfiller for "downloadWithThisGivenName".

**Comment by regular-citizen** [comment]
> Fortunately, it can be polyfilled quite easily: https://github.com/jimmywarting/native-file-system-adapter/

I didn't know about this, this is very cool. It seems that it should also be able to handle drag and drops, which we could use for imports.

**Comment by calintat** [comment]
> > Fortunately, it can be polyfilled quite easily: https://github.com/jimmywarting/native-file-system-adapter/
> 
> I didn't know about this, this is very cool. It seems that it should also be able to handle drag and drops, which we could use for imports.

Oh that would be really cool. We could also let people drag and drop a .hom file into a signature (#523).

**Comment by regular-citizen** [comment]
I'll close this PR and have a crack at integrating that in the coming days.

**Pull request closed without merging**
