### PR TITLE
Stash diagrams

### PR DESCRIPTION
**Pull request by calintat**
(I wrote this a while ago so I thought I'd push it in case anyone wants to take it further).

Basic implementation of #86 in a similar style to `git stash`. It has no UI right now, just keybindings (`+` to stash, `-` to pop).

### CODE REVIEW

**Comment by regular-citizen** [comment]
Thanks for coding this, I like this a lot.

Two things:
- Stashing a diagram, then deleting a generator used in it, results in a panic when unstashing it.
- You should not be able to unstash a diagram if the current workspace diagram is not empty in my opinion.

Should we support keeping the current diagram while stashing it?

**Comment by calintat** [comment]
I think it's fine if unstashing works even if the workspace is not empty, because selecting a generator also works when the workspace is non-empty. Plus you can always undo if you make a mistake.

**Comment by calintat** [comment]
I think it's weird if stashing didn't clear the workspace.

**Comment by regular-citizen** [comment]
> I think it's weird if stashing didn't clear the workspace.

Yeah I have realised that we can already keep the current diagram by saving it as source/target, then selecting it again and stashing it. So the current flow works.

**Comment by calintat** [comment]
Once we figure out the UI, we can also have an action that recovers the top stashed diagram without removing it from the stack (similar to `RecoverBoundary`).

**Pull request merged**
