### PR TITLE
Empty workspace message (#512)

### PR DESCRIPTION
**Pull request by regular-citizen**
Feedback welcome

### CODE REVIEW

**Comment by jamievicary** [comment]
Thanks Chiara this is great! Could we make it grey please rather than black? Then I will be happy.

**Comment by regular-citizen** [comment]
> Thanks Chiara this is great! Could we make it grey please rather than black? Then I will be happy.

I assumed this referred to the logo, but let me know if you also want the text lighter.

I have a separate patch with a safety mechanism which disables the "?" keyboard shortcut when the signature contains "interesting" stuff. This is to avoid users being teleported away to the tutorial in the middle of a complicated proof. Right now, it seems that the "unsaved work" mechanism is working effectively, but we may want to be extra careful.

Let me know also on this front, otherwise we are good to merge as far as I am concerned.

**Comment by calintat** [comment]
This looks fantastic, thanks Chiara!

I just pushed a small commit reordering the shortcuts, I think we should merge this!

**Comment by calintat** [comment]
> > Thanks Chiara this is great! Could we make it grey please rather than black? Then I will be happy.
> 
> I assumed this referred to the logo, but let me know if you also want the text lighter.
> 
> I have a separate patch with a safety mechanism which disables the "?" keyboard shortcut when the signature contains "interesting" stuff. This is to avoid users being teleported away to the tutorial in the middle of a complicated proof. Right now, it seems that the "unsaved work" mechanism is working effectively, but we may want to be extra careful.
> 
> Let me know also on this front, otherwise we are good to merge as far as I am concerned.

I wouldn't worry too much about users accidentally pressing '?'.

**Comment by jamievicary** [comment]
Thanks Chiara! I was imagining everything being gray including the text.
This makes it a bit less intrusive for expert users.

**Comment by regular-citizen** [comment]
> I was imagining everything being gray including the text.

Done, let me know if this works, otherwise I can make it even lighter.

**Comment by calintat** [comment]
Can we also make the shortcuts grey to match the text?

**Pull request merged**
