### PR TITLE
Refactor sidebar buttons

### PR DESCRIPTION
**Pull request by doctorn**
No idea if you guys think this is a good idea but I've started pulling out some of the purely UI bits into a components library. This commit also adds a stub for the settings menu alognside some general cleaning for the sidebar buttons. Let me know what you think!

@zrho @NickHu

### CODE REVIEW

**Comment by NickHu** [comment]
It's looking good to me so far!

**Comment by jamievicary** [comment]
Thanks for this Nathan! If you're happy that everything is clean and non-contentious, you can go ahead and merge it into master. That way I can check it out more easily via beta.homotopy.io.

**Comment by zrho** [comment]
LGTM

**Comment by doctorn** [comment]
I don’t think I have permission to merge

**Comment by jamievicary** [comment]
> I don’t think I have permission to merge

I have now given you and Akvile admin rights.

**Pull request merged**
