### PR TITLE
Refactor graphs in `homotopy_core`

### PR DESCRIPTION
**Pull request by calintat**
`GraphBuilder` is now generic in the `RewriteAllocator` so it can also explode cubical graphs in cubicalisation.

I also simplified the keys since they are always coordinates.

### CODE REVIEW

**Comment by calintat** [comment]
It is now generic in the `RewriteAllocator` so it can also explode cubical graphs in cubicalisation.

**Comment by NickHu** [comment]
> I also simplified the keys since they are always coordinates.

I feel like there was a reason why it's generic, but I can't remember right now.

**Comment by calintat** [comment]
> > I also simplified the keys since they are always coordinates.
> 
> I feel like there was a reason why it's generic, but I can't remember right now.

Think about it this way: if a node has coordinate `[a, b, c]`, its key will be `f(a, f(b, f(c)))` so you could always compute the key from the coordinate, so we don't lose any generality by getting rid of the key and replacing it with a coordinate.

**Review by doctorn — COMMENTED** [review]
Looks really good!

**Pull request merged**
