### PR TITLE
Source/target preview + Default names for proof cells

### PR DESCRIPTION
**Pull request by H-Yulong**
Implemented source/target preview and default names for proof cells

### CODE REVIEW

**Comment by calintat** [comment]
You can run 'rustfmt' to fix the linter errors. Also if you look at the CI, it tells you where the errors are.

**Comment by calintat** [comment]
Also what Nick said last week was to make work in a branch on the main repo rather than a fork, so that Firebase can generate a preview URL for your PR. But you don't have to do that for this, just keep that in mind for next time :)

**Comment by calintat** [comment]
One more thing, this PR addresses multiple issues. In the future, please split that into multiple PRs.

**Comment by H-Yulong** [comment]
Thanks! The problem is now fixed and it's ready to merge. I created a branch on the main repo and will work there from now.

For reference, this PR addresses the following problems:
- #510 
- #511
- #529

**Comment by calintat** [comment]
Brilliant job, thanks Yulong!

I'll let you do the honour of merging it. Also you can close the issues as fixed.

**Comment by calintat** [comment]
Actually leave #511 as open, as there are more things to do with the about dialog. But the others can be closed.

**Pull request merged**
