### PR TITLE
Substantial improvements to signature UI

### PR DESCRIPTION
**Pull request by thud**
This should allow the user to (optionally) preview each generator in the signature panel.

It should allow the user to toggle between generator previews and source/target previews.

### CODE REVIEW

**Comment by calintat** [comment]
Thanks Jasper! This is looking great, we just need to tweak the UI now.
- We need a checkbox "Single image" for toggling between a single image and source/target.
- The toggle should be disabled in 0D, default to true in 1D and 2D, and default to false in 3D and above.
- Can we move the dimension between the settings icon and name so everything except the preview is left aligned.
- Also can you try to make the settings icon a light/dark grey depending on the generator colour.
- We definitely need to increase the size of the previews as they are too small right now.
- Another thing, it would be nice to have a toggle to disable the previews altogether so you can have a more compact view. I don't know if this should be a global toggle for the signature or per generator. I am favour of the former, but anyway this is not a priority right now.

**Comment by thud** [comment]
0449227 addresses a few of these, though more is still needed to be done.

**Comment by thud** [comment]
Written update (post standup with JV): Signature previews are good to stay small (some indication of invertible/framed/oriented would be good).

**Comment by doctorn** [comment]
I just tested this out -- amazing stuff!! I did notice that it looks like you've added a settings cog to the folders as well as the generators? Just wanted to check that was intentional?

**Comment by thud** [comment]
Yeah thanks, the folders could do with some rework. The colours are also pretty horrible at the moment so hopefully it can look a lot nicer. I do think we need the cog for renaming purposes (disables draggable).

**Comment by thud** [comment]
Note that preview caching is currently too aggressive.

**Comment by thud** [comment]
As of now, caching is overly-careful rather than overly-aggressive ensuring correctness.

**Comment by calintat** [comment]
This is looking really good Jasper. Just a few comments and then we should merge this:
- We should default to "single image" in 1D/2D and "source/target" in 3D and above. We could even disable "source/target" altogether in 1D/2D as it doesn't really tell you much and it's a bit ugly.
- The unicode arrow symbol doesn't work on any of my machines :( Tbh I'm not so keen on the symbol, I would suggest removing it.
- I don't like the idea of using boxes when running out of colours. That should be something the user toggles on purpose.
- Can we move the drawer resizing into a separate PR? It looks like it might need some more polishing and we shouldn't wait on that to merge this PR.

**Comment by thud** [comment]
Great, good to hear it, I'll look to get this merged imminently.

> We should default to "single image" in 1D/2D and "source/target" in 3D and above. We could even disable "source/target" altogether in 1D/2D as it doesn't really tell you much and it's a bit ugly.
- [ ] Great sounds good, I'll commit that now.

> The unicode arrow symbol doesn't work on any of my machines :( Tbh I'm not so keen on the symbol, I would suggest removing it.
- [ ] Good

> I don't like the idea of using boxes when running out of colours. That should be something the user toggles on purpose.
- [ ] Easy fix, apologies

> Can we move the drawer resizing into a separate PR? It looks like it might need some more polishing and we shouldn't wait on that to merge this PR.
- [ ] Yeah fair enough, it's still definitely experimental.

**Comment by thud** [comment]
Great, good to hear it, I'll look to get this merged imminently.

> We should default to "single image" in 1D/2D and "source/target" in 3D and above. We could even disable "source/target" altogether in 1D/2D as it doesn't really tell you much and it's a bit ugly.
- [ ] Great sounds good, I'll commit that now.

> The unicode arrow symbol doesn't work on any of my machines :( Tbh I'm not so keen on the symbol, I would suggest removing it.
- [ ] Good

> I don't like the idea of using boxes when running out of colours. That should be something the user toggles on purpose.
- [ ] Easy fix, apologies

> Can we move the drawer resizing into a separate PR? It looks like it might need some more polishing and we shouldn't wait on that to merge this PR.
- [ ] Yeah fair enough, it's still definitely experimental.

**Comment by calintat** [comment]
Thanks Jasper. Feel free to merge this if you want.

**Pull request merged**
