### PR TITLE
Better style picker

### PR DESCRIPTION
**Pull request by thud**
This changes the functionality of the generator style-picking UI to allow for preferences such as invertibility (#589).
It also eliminates the intermediate 'edit' state from this UI for simplicity.

### CODE REVIEW

**Comment by calintat** [comment]
Amazing!

Just a few comments:
- can we move invertibility to the top,
- can we make the whole region around the text/checkbox clickable
- is it possible to disable the checkbox on certain generators (e.g. 0-generators)?

**Comment by thud** [comment]
No problem, shouldn't take long...

**Comment by calintat** [comment]
Sorry I broke your branch :(

**Comment by thud** [comment]
I've pushed a fix for these features.

This removes the invertibility option entirely from 0d generators. If preferred, I can change to keep displaying but disable input.

**Comment by calintat** [comment]
Brilliant, thanks Jasper!

I think it's better to remove the checkbox, rather than disabling it.

**Comment by thud** [comment]
Great

**Pull request merged**
