### PR TITLE
Add error information to well-formed checker

### PR DESCRIPTION
**Pull request by calintat**

### CODE REVIEW

**Comment by calintat** [comment]
The return type of the well-formed check was changed from `bool` to `Result<(), MalformedDiagram>` for diagrams and `Result<(), MalformedRewrite>` for rewrites, where `MalformedDiagram` and `MalformedRewrite` are some error types that specify why the diagram/rewrite fails the check.

**Comment by jamievicary** [comment]
Great, is it easy to propagate this info as a toast? Would that be useful?

**Comment by zrho** [comment]
It'd probably be best if that info showed up in the console instead of the toast so that one can look at it in peace.

**Comment by calintat** [comment]
I agree with Lukas. This is for debugging purposes only.

**Pull request merged**
