### PR TITLE
Implement smoothing

### PR DESCRIPTION
**Pull request by NickHu**
I can't figure out why this allows for results which don't typecheck. As far as I can tell, the result is being typechecked: https://github.com/homotopy-io/homotopy-rs/blob/e857bc74ab39191ac1fb46b22a45aac2ebd8bc93/homotopy-core/src/expansion.rs#L74
but it's still allowing for things like smoothing an endomorphism composed with itself (the rewrite generated by this action should definitely not typecheck). Any ideas @zrho?

### CODE REVIEW

**Comment by jamievicary** [comment]
Looks like this can be merged, is there any reason not to at the moment?

**Comment by NickHu** [comment]
Yes, it allows you to build diagrams which fail to typecheck

**Comment by jamievicary** [comment]
Ah yes of course sorry.

**Comment by NickHu** [comment]
I think the issues I mentioned before have been resolved by 90f526137790816ee44bbfb6ed7eb2c95fadd090. At least, an endomorphism composed with itself doesn't smooth anymore like it used to. Ready for more testing before merging @jamievicary @zrho

**Comment by jamievicary** [comment]
Nick has the typechecking issue been resolved yet?

**Comment by NickHu** [comment]
I think I will go ahead and merge this seeing as the well-formed-ness checker is coming soon

**Pull request merged**
